                                    Anand International College of Engineering
                                    Subject – Data Science with AI & MLops
                                    Topic – NumPy
                                        
                                            Assignment 4:

In [2]:
import numpy as np


1. Create a 5 × 5 NumPy matrix containing numbers from 1 to 25 and
print:
○ The first row
○ The last column
○ The diagonal elements

In [3]:
arr=np.arange(1,26).reshape((5,5))
print(arr)
print("First row :",arr[0,])
print("last column :",arr[0:,-1])

print("digonal element ",np.diag(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First row : [1 2 3 4 5]
last column : [ 5 10 15 20 25]
digonal element  [ 1  7 13 19 25]


2. Create two 3 × 3 matrices and perform matrix addition, subtraction,
and matrix multiplication.


In [4]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2= np.array([[4,8,7],[9,5,4],[6,2,1]])
print("addition\n",arr1+arr2)
print("subtraction\n",arr1-arr2)
print("matrix multiplication\n",np.dot(arr1,arr2))

addition
 [[ 5 10 10]
 [13 10 10]
 [13 10 10]]
subtraction
 [[-3 -6 -4]
 [-5  0  2]
 [ 1  6  8]]
matrix multiplication
 [[ 40  24  18]
 [ 97  69  54]
 [154 114  90]]


3. Create a NumPy array of numbers from 1 to 100 and print all numbers
divisible by 3 using Boolean indexing.


In [5]:
arr = np.arange(1, 101)

print(arr[arr % 3 == 0])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


4. Create a 4 × 4 matrix and replace all even numbers with 0.


In [6]:
arr=np.arange(1,17).reshape(4,4)
arr[arr%2==0]=0
print(arr)

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


5. Create a 5 × 5 matrix of random integers and find:
○ Maximum value
○ Minimum value
○ Mean
○ Median

In [7]:
arr = np.random.randint(1, 100, (5, 5))
print(arr)
print("Maximum value",np.max(arr))
print("Minimum value",np.min(arr))
print("Mean",np.mean(arr))
print("Median",np.median(arr))

[[ 5 76 19 28  5]
 [54 49 40 24 94]
 [ 8 45 29 78 80]
 [55 96 28 97 17]
 [59 40 35 62 47]]
Maximum value 97
Minimum value 5
Mean 46.8
Median 45.0


6. Create a NumPy array containing 20 random numbers and sort it in
ascending and descending order.

In [8]:
arr = np.random.randint(1, 100, (20))
print(arr)
print("ascending order ",np.short(arr))
print("descending order ",np.short(arr[::-1]))

[76 32 84 32 33 14 37 72 77 13 20 29 14 46 34 16 64 57 45 24]
ascending order  [76 32 84 32 33 14 37 72 77 13 20 29 14 46 34 16 64 57 45 24]
descending order  [24 45 57 64 16 34 46 14 29 20 13 77 72 37 14 33 32 84 32 76]


7. Create a 6 × 6 matrix and print:
○ Main diagonal
○ Upper triangular part
○ Lower triangular part


In [9]:
arr = np.arange(1, 37).reshape(6, 6)

print('matrix\n',arr)
print("Main Diagonal ", np.diag(arr))
print("Upper Triangular \n", np.triu(arr))
print("Lower Triangular \n", np.tril(arr))

matrix
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Main Diagonal  [ 1  8 15 22 29 36]
Upper Triangular 
 [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
Lower Triangular 
 [[ 1  0  0  0  0  0]
 [ 7  8  0  0  0  0]
 [13 14 15  0  0  0]
 [19 20 21 22  0  0]
 [25 26 27 28 29  0]
 [31 32 33 34 35 36]]


8. Create a NumPy array of 20 elements and reshape it into:
○ 4 × 5 matrix
○ 2 × 10 matrix
○ 5 × 4 matrix


In [10]:
arr=np.random.randint(1,100,(20))
print(arr)
print("\n4 × 5 matrix \n",arr.reshape((4,5)))
print("\n2 × 10 matrix \n",arr.reshape((2,10)))
print("\n5 × 4 matrix \n",arr.reshape((5,4)))


[17 48 61 12 28 33 63 97 56 82 50 15  6 58 43 68 23 97 12 57]

4 × 5 matrix 
 [[17 48 61 12 28]
 [33 63 97 56 82]
 [50 15  6 58 43]
 [68 23 97 12 57]]

2 × 10 matrix 
 [[17 48 61 12 28 33 63 97 56 82]
 [50 15  6 58 43 68 23 97 12 57]]

5 × 4 matrix 
 [[17 48 61 12]
 [28 33 63 97]
 [56 82 50 15]
 [ 6 58 43 68]
 [23 97 12 57]]


9. Create a 5 × 5 matrix and calculate the sum of:
○ Each row
○ Each column

In [11]:
arr = np.arange(1, 26).reshape(5, 5)

print("Matrix:\n", arr)
print("Each row Sum:", np.sum(arr, axis=1))
print("Each column Sum:", np.sum(arr, axis=0))

Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Each row Sum: [ 15  40  65  90 115]
Each column Sum: [55 60 65 70 75]


10. Create two arrays and find all common elements between them.

In [12]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
print("Common Elements:", np.intersect1d(arr1, arr2))

Common Elements: [4 5 6]


11. Create a 5 × 5 matrix and find the position (row and column index)
of the largest element.


In [13]:
arr = np.random.randint(1, 100, (5, 5))
print("Matrix:\n", arr)
max_value = np.max(arr)
row, col = np.where(arr == max_value)
print("largest element ",max_value)
print(f"position (row , column) : {row[0]}, {col[0]}")

Matrix:
 [[69 54 42 68 18]
 [84 72 36 45 32]
 [90 19  1 61 43]
 [35 15 90 29 76]
 [30 81 16 49 16]]
largest element  90
position (row , column) : 2, 0


12. Create a dataset of students' marks using a NumPy array and find:
● Highest marks
● Lowest marks
● Average marks
● Students scoring above average

In [14]:
marks = np.array([65, 78, 92, 55, 88, 73, 95, 60])

avg = np.mean(marks)

print("marks:", marks)
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))
print("Average Marks:", avg)
print(f"Students scoring above {avg}:", marks[marks > avg])

marks: [65 78 92 55 88 73 95 60]
Highest Marks: 95
Lowest Marks: 55
Average Marks: 75.75
Students scoring above 75.75: [78 92 88 95]
